# Generated by Django 4.2.7 on 2024-07-01 17:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"verbose_name_plural": "Dishes"},
        ),
    ]
