# Generated by Django 5.0.6 on 2024-07-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_category_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
    ]
